### ISSUE TITLE
Cannot find module './src/ParseError' from '<path>/node_modules/katex/dist'

### ISSUE THREAD

**Issue by ioanac95** [tylingsoft/markdown-it-latex#1]
When I'm importing markdown-it-latex in my preview.js file (`import markdownItLatex from 'markdown-it-latex';`), I get this error:
`Error: Cannot find module './src/ParseError' from '/home/bianca/Documents/<path>/node_modules/katex/dist'
    at /home/bianca/.nvm/versions/node/v7.5.0/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:55:21
    at load (/home/bianca/.nvm/versions/node/v7.5.0/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/bianca/.nvm/versions/node/v7.5.0/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /home/bianca/.nvm/versions/node/v7.5.0/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:112:15)`

The src folder is actually not in katex/dist/, but in katex/, so I'm confused about why it looks for it in dist... 
I installed markdown-it-latex first via npm, then via yarn just to see if there was any difference. I also tried to `require('markdown-it-latex');` and the same error is shown.

I'm using browserify together with babelify to bundle the code for the browser, as such `browserify preview.js -o bundle.js -t babelify` and in my package.json I added `"babel": {
    "presets": [
      "env"
    ]
  }`

This approach works for require-ing "markdown-it", together with some plugins like "markdown-it-sub". Only adding this import throws this error. Do you know what might be causing this?

**Comment by tylerlong** [comment]
No, I don't know.

I use webpack and it works like a charm: https://github.com/tylingsoft/markdown-core/blob/master/src/engine.js#L4

Please report a bug to the browerify project.
